filter {
  mutate {
    remove_field => ["source_ip:"]
    add_field => { "source_ip" => "%{[host][ip]}" }
  }

  grok {
    match => {
      "message" => [
        '<%{POSINT:syslog_pri}>%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT}\])?: %{GREEDYDATA:syslog_message}',
        '<%{INT:syslog_pri}>1 %{TIMESTAMP_ISO8601:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{PROG:syslog_program} (?:%{WORD}|-)\s+(?:%{WORD}|-) %{GREEDYDATA:syslog_message}'
      ]
    }
    remove_field => ["@version", "syslog_pri"]
  }

  date {
    match => ["syslog_timestamp", "ISO8601", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss"]
    target => "@timestamp"
    timezone => "America/Havana"
    locale => "en"
    tag_on_failure => []
  }

  mutate {
    replace => {
      "indice_local" => "%{+YYYY.MM.dd}"
    }
  }

  date {
    match => ["syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss", "ISO8601"]
    target => "syslog_timestamp"
    timezone => "America/Havana"
    locale => "en"
    tag_on_failure => []
  }

  mutate {
    lowercase => ["syslog_program"]
  }

  mutate {
    remove_field => ["tags"]
    add_field => { "tags" => [] }
  }

}

