filter {
  if !("log_procesado" in [tags]) {

    if [source_ip] in ["10.12.1.5", "10.12.1.9", "10.12.1.74", "10.12.1.73", "10.12.1.72", "10.12.1.80"] and ([syslog_program] == "haproxy" or [message] =~ /haproxy\[[0-9]+\]:/ ) {

      mutate {
        replace => { "index_name" => "uclv-ha-inverso" }
        add_tag => ["log_procesado", "haproxy"]
        copy => { "syslog_message" => "haproxy_raw_message" }
      }

      grok {
        match => {
        "message" => [ "^<%{INT:syslog_pri}>%{SYSLOGTIMESTAMP:syslog_timestamp} %{DATA:syslog_program}\[%{INT:pid}\]: %{IP:client_ip}:%{INT:client_port:int} \[%{DATA:haproxy_timestamp}\] %{NOTSPACE:haproxy_frontend} " ]
        }
        tag_on_failure => ["_haproxy_frontend_parse_failed"]
      }

      if [haproxy_frontend] in ["https-in~", "http-in~" , "http-in", "https-in"] {

        grok {
          match => {
            "message" => ["^<%{INT}>%{SYSLOGTIMESTAMP} %{DATA}\[%{INT}\]: %{IP}:%{INT} \[%{DATA}\] %{NOTSPACE} %{NOTSPACE:haproxy_backend}/%{NOTSPACE:haproxy_server} %{INT:Tq:int}/%{INT:Tw:int}/%{INT:Tc:int}/%{INT:Tr:int}/%{INT:Tt:int} %{INT:http_status:int} %{INT:bytes_read:int} %{NOTSPACE:req_cookie} %{NOTSPACE:res_cookie} %{NOTSPACE:termination_state} %{INT:actconn:int}/%{INT:feconn:int}/%{INT:beconn:int}/%{INT:srv_conn:int}/%{INT:retries:int} %{INT:srv_queue:int}/%{INT:backend_queue:int} \{%{GREEDYDATA:captured_request_headers}\} \"%{WORD:http_method} %{DATA:http_request} HTTP/%{DATA:http_version}\""]
          }
          tag_on_failure => ["_haproxy_http_parse_failed"]
        }

        mutate {
          add_field => { "haproxy_mode" => "http" }
        }

      } else if [haproxy_frontend] in ["mqtt-in", "smtp_ssl" , "imapssl" , "imap" , "smtp"  ]{

        grok {
          match => {
            "message" => [
              "^%{DATA} %{DATA} %{DATA}\[%{DATA}\]: %{IP}:%{INT} \[%{DATA}\] %{NOTSPACE} %{NOTSPACE:haproxy_backend}/%{NOTSPACE:haproxy_server} %{INT:Tw:int}/%{INT:Tc:int}/%{INT:Tt:int} %{INT:bytes_read:int} %{NOTSPACE:termination_state} %{INT:actconn:int}/%{INT:feconn:int}/%{INT:beconn:int}/%{INT:srv_conn:int}/%{INT:retries:int} %{INT:srv_queue:int}/%{INT:backend_queue:int}$"
            ]
          }
          tag_on_failure => ["_haproxy_tcp_parse_failed"]
        }

        mutate {
          add_field => { "haproxy_mode" => "tcp" }
        }

      } else {
        mutate {
          add_tag => ["_haproxy_unknown_frontend"]
        }
      }
    }
  }
}


