filter {
  if !("log_procesado" in [tags]) {

    #--------firewall--------
    if [syslog_program] =~ /filterlog/ or [message] =~ /filterlog/ {

      mutate {
        add_field => {"index_name" => "uclv-firewall"}
      }

      grok {
        match => {
          "syslog_message" => "-\s*%{INT:rule_num},,,%{INT:tracker_id},%{WORD:interface},%{WORD:reason},%{WORD:action},%{WORD:direction},%{INT:ip_version},%{WORD:ip_flags},,%{INT:ttl},%{INT:id},%{INT:offset},%{WORD:df},%{INT:proto_id},%{WORD:proto},%{INT:length},%{IP:src_ip},%{IP:dst_ip},%{INT:src_port},%{INT:dst_port}(?:,%{INT:data_length})?(?:,%{GREEDYDATA:options})?"
        }
        tag_on_failure => ["_grokparsefailure_firewall"]
        remove_field => ["proto_id", "length", "ip_flags", "offset", "ip_version"]
      }

      if !("_grokparsefailure_firewall" in [tags]) {
        mutate {
          add_tag => ["log_procesado"]
        }
      }
    }

    #----------captivo-----------
    else if [message] =~ /(logportalauth)/ {

      mutate {
        add_field => {"index_name" => "uclv-captivo"}
      }

      grok {
        match => {
          "syslog_message" => [
            'Zone: %{WORD:uclv_zone} - %{DATA:uclv_event_type}: %{USERNAME:uclv_username}, %{MAC:uclv_mac_address}, %{IP:uclv_ip_address}'
          ]
        }
        tag_on_failure => ["_grokparsefailure_captivo"]
        add_field => { "unparsed_message" => "%{message}" }
      }

      if !("_grokparsefailure_captivo" in [tags]) {
        mutate {
          add_tag => ["log_procesado"]
        }
      }
    }

    #----------logs del sistema------
    else if ([message] =~ /(?i)(error|reboot|daemon|Memory|CPU)/ or [syslog_program] =~ /(?i)pf/) {

      mutate {
        add_field => {"index_name" => "uclv-sistema"}
      }

      grok {
        match => {
          "syslog_message" => "%{DATA:system_component}: %{GREEDYDATA:system_message}"
        }
        tag_on_failure => ["_grokparsefailure_sistema"]
      }

      if !("_grokparsefailure_sistema" in [tags]) {
        mutate {
          add_tag => ["log_procesado"]
        }
      }
    }

    #----------NGINX ACCESS LOGS------
    else if [syslog_program] =~ /nginx/ {

      mutate {
        add_field => {"index_name" => "uclv-nginx"}
      }

      grok {
        match => {
          "syslog_message" => '(?:%{NOTSPACE:junk_field}\s+){1,4}%{IPORHOST:clientip}\s+%{NOTSPACE:ident}\s+%{NOTSPACE:auth}\s+\[%{HTTPDATE:timestamp}\]\s+"%{WORD:http_verb}\s+%{URIPATH:request_path}\s+HTTP/%{NUMBER:http_version}"\s+%{NUMBER:response_code}\s+%{NUMBER:bytes}\s+"%{DATA:referrer}"\s+"%{GREEDYDATA:user_agent}"'
        }
        tag_on_failure => ["_grokparsefailure_nginx"]
        remove_field => ["timestamp"]
      }

      if !("_grokparsefailure_nginx" in [tags]) {
        mutate {
          add_tag => ["log_procesado"]
        }
      }
    }

    #----------otros-----------
    else {
      mutate {
        add_field => { "index_name" => "uclv-otros" }
        add_tag => ["log_procesado"]
      }
    }
  }

}
